# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUjbHBWNZgesoyhM0oHd975mrxjmRbXr
"""

import json
import os
from datetime import datetime

# ---------------------------
# ATM Simulator Project
# ---------------------------

DATA_FILE = "accounts.json"


# ---------- Helper Functions ----------
def load_accounts():
    """Load account data from file"""
    if not os.path.exists(DATA_FILE):
        return {}
    with open(DATA_FILE, "r") as f:
        return json.load(f)


def save_accounts(accounts):
    """Save account data to file"""
    with open(DATA_FILE, "w") as f:
        json.dump(accounts, f, indent=4)


# ---------- Account Class ----------
class Account:
    def __init__(self, name, pin, balance=0.0):
        self.name = name
        self.pin = pin
        self.balance = balance
        self.transactions = []

    def deposit(self, amount):
        if amount <= 0:
            print("❌ Enter a valid amount.")
            return
        self.balance += amount
        self.transactions.append(f"{datetime.now()}: Deposited ₹{amount}")
        print(f"✅ ₹{amount} deposited successfully.")

    def withdraw(self, amount):
        if amount <= 0:
            print("❌ Enter a valid amount.")
            return
        if amount > self.balance:
            print("❌ Insufficient balance.")
            return
        self.balance -= amount
        self.transactions.append(f"{datetime.now()}: Withdrew ₹{amount}")
        print(f"✅ ₹{amount} withdrawn successfully.")

    def check_balance(self):
        print(f"💰 Current Balance: ₹{self.balance}")

    def show_transactions(self):
        if not self.transactions:
            print("📄 No transactions yet.")
        else:
            print("📜 Transaction History:")
            for t in self.transactions:
                print(" -", t)


# ---------- Main ATM System ----------
class ATM:
    def __init__(self):
        self.accounts = load_accounts()

    def create_account(self):
        name = input("Enter your name: ")
        pin = input("Set a 4-digit PIN: ")
        if not pin.isdigit() or len(pin) != 4:
            print("❌ PIN must be 4 digits.")
            return
        if name in self.accounts:
            print("⚠️ Account already exists.")
            return

        self.accounts[name] = {
            "pin": pin,
            "balance": 0.0,
            "transactions": []
        }
        save_accounts(self.accounts)
        print("🎉 Account created successfully!")

    def login(self):
        name = input("Enter your name: ")
        pin = input("Enter your PIN: ")

        if name not in self.accounts or self.accounts[name]["pin"] != pin:
            print("❌ Invalid name or PIN.")
            return None

        print(f"👋 Welcome back, {name}!")
        data = self.accounts[name]
        acc = Account(name, pin, data["balance"])
        acc.transactions = data["transactions"]
        return acc

    def update_account(self, account):
        """Save updates after transactions"""
        self.accounts[account.name] = {
            "pin": account.pin,
            "balance": account.balance,
            "transactions": account.transactions
        }
        save_accounts(self.accounts)


# ---------- Main Program Loop ----------
def main():
    atm = ATM()

    while True:
        print("\n===== 🏦 ATM MENU =====")
        print("1. Create Account")
        print("2. Login")
        print("3. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            atm.create_account()

        elif choice == "2":
            acc = atm.login()
            if acc:
                while True:
                    print("\n--- Account Menu ---")
                    print("1. Check Balance")
                    print("2. Deposit")
                    print("3. Withdraw")
                    print("4. Transaction History")
                    print("5. Logout")

                    ch = input("Enter choice: ")

                    if ch == "1":
                        acc.check_balance()
                    elif ch == "2":
                        amt = float(input("Enter amount to deposit: ₹"))
                        acc.deposit(amt)
                        atm.update_account(acc)
                    elif ch == "3":
                        amt = float(input("Enter amount to withdraw: ₹"))
                        acc.withdraw(amt)
                        atm.update_account(acc)
                    elif ch == "4":
                        acc.show_transactions()
                    elif ch == "5":
                        print("👋 Logged out successfully.")
                        atm.update_account(acc)
                        break
                    else:
                        print("❌ Invalid choice. Try again.")

        elif choice == "3":
            print("🙏 Thank you for using the ATM. Goodbye!")
            break

        else:
            print("❌ Invalid option. Please try again.")


if __name__ == "__main__":
    main()
